behaviors:
  My Behavior:
    trainer_type: ppo

    hyperparameters:
      batch_size: 512
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 0.0

    behavioral_cloning:
      demo_path: C:/Users/g2294/Desktop/UnityProjects/SpotlightGameJam_Demos/All/Level2.demo
      strength: 5000.0
      steps: 160000
      batch_size: 1024
      num_epoch: 12
      samples_per_update: 0

    keep_checkpoints: 8
    checkpoint_interval: 20000
    threaded: true
    max_steps: 160000
    time_horizon: 128
    summary_freq: 10000
